#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import re
import subprocess

parser = argparse.ArgumentParser(description="Smart switch")
parser.add_argument("branch", help="Switch to a specified branch.")
args = parser.parse_args()


current_branch = subprocess.check_output(["git", "branch", "--show-current"], text=True).strip()

# try to stash the current state setting a parseable message with the branch
subprocess.check_output(["git", "stash", "--message", f"[smart switch] {current_branch}"], text=True)

# switch
subprocess.check_output(["git", "switch", args.branch])

# this is the same than args.branch but also expand references like "-"
target_branch = subprocess.check_output(["git", "branch", "--show-current"], text=True).strip()

# list stashes to find if there is something to pop
stashes_list = subprocess.check_output(["git", "stash", "list"], text=True)
stashes = {branch_name: stash_index for (stash_index, branch_name) in re.findall(r"stash@\{(\d+)\}\: .*: \[smart switch\] (.*)", stashes_list)}

stash_index = stashes.get(target_branch)

if stash_index is not None:
    subprocess.check_output(["git", "stash", "pop", "--index", stash_index])